filter:
    excluded_paths:
        - bin/*
        - src/legacy/*
        - src/server/*
        - src/testrunner/*
checks:
    php: true
coding_style:
    php: {  }
tools:
    external_code_coverage: true
